### ISSUE TITLE
[Feature] 231122 UI 통합 수정 사항

### ISSUE THREAD

**Issue by dkin12** [georgeois10/georgeois_AOS#18]
## ✅ Description
231122 UI 통합 수정 사항 

## ✔️ TODO
**게시판** 
- [x] 서치바 클릭시 키보드 올리기 
- [x] 게시판 플로팅 버튼을 서치뷰 아래로 
- [x] 게시판 댓글 채팅방과 동일하게 변경

**홈** 
- [x] main에서 홈이 아닌 다른 곳 ( mainChatting, mainBoard, mainMyPage ) 에서 백 버튼 ( 뒤로가기 ) 클릭시 홈으로 
- [x] 뒤로가기 클릭시 셀렉아이팀 색상도 맞게 변경하기 
- [x]  홈으로 뒤로가기 한번할때 흰색 배경나오는거 막고, 2번 뒤로가기 하면 종료
- [x] 카드뷰 외곽선 lightGray처리 
- [x] 카드뷰 백그라운드 투명 처리 
- [x] 카드뷰 금액 , 원 처리
