### ISSUE TITLE
[Feature] 오픈채팅 & 마이페이지 화면 구성 

### ISSUE THREAD

**Issue by YonjjinJang** [georgeois10/georgeois_AOS#7]
## ✅ Description
오픈채팅 & 마이페이지 카테고리 UI 구성

## ✔️ TODO
- [x] 오픈채팅 메인 화면 구성
- [x] 오픈채팅 만들기 화면 구성
- [x] 채팅방 구성
- [x] 채팅방 가계부 화면 구성
- [x] 마이페이지 메인 화면 구성
- [x] 프로필 수정 화면 구성
- [x] 비밀번호 변경 화면 구성
- [x] 지출&수입 카테고리 변경 화면 구성
- [x] 내가 쓴 글 화면 구성

## ETC
힝
